### PR TITLE
Added ApfsSupportPkg support

### PR DESCRIPTION
**Pull request by athlonreg**
Hi micky1979
    From Rev 4540, new driver developed by savvas https://github.com/acidanthera/ApfsSupportPkg/. It performs loading the driver from APFS container by DiskIO protocol.
    I have added support for building the driver,a big thx for your work!´◡`

### CODE REVIEW

**Comment by philippetev** [comment]
Just added that support to the script, along with some rearrangements. Thanks anyway!

**Comment by athlonreg** [comment]
@philippetev I see, so we can use the work branch script to build clover?

**Comment by philippetev** [comment]
Just added it to the main repo.

**Comment by athlonreg** [comment]
ok, get it, thx

**Pull request closed without merging**
